name: Release docker image

on: [push, pull_request]

permissions:
  packages: write

jobs:
  docker-amd:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - run: go run ./lib/docker $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/upload-artifact@v4
        with:
          name: review-fonts-docker
          path: tmp/fonts.pdf

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: cdp-log-docker
          path: tmp/cdp-log

  docker-arm:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - run: go run ./lib/docker $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ARCH: arm
